local process = Process("attackMode")

process:onStart(function(this)

    local bubble = this:bubble()

    bubble.DarkRanger = Unit(TPL_UNIT.DarkRanger, Player(1), 0, -1000, 270)
    bubble.DarkRanger:flyHeight(300)
    bubble.DarkRanger:weaponHeight(75)
    bubble.DarkRanger:attackModePush(AttackMode()
        :mode("missile")
        :missileModel("BlackArrowMissile")
        :homing(true)
        :height(300)
        :speed(800))
    --bubble.DarkRanger:attackModePush(AttackMode()
    --    :mode("missile")
    --    :missileModel("BlackArrowMissile")
    --    :homing(false)
    --    :height(0)
    --    :speed(800)
    --    :shake("rand"))
    --bubble.DarkRanger:attackModePush(AttackMode()
    --    :mode("lightning")
    --    :lightningType(LIGHTNING_TYPE.thunderRed)
    --    :focus(10))

    bubble.u0 = Unit(TPL_UNIT.AttackMode0, PlayerAggressive, -500, -500, 270)
    bubble.u1 = Unit(TPL_UNIT.AttackMode1, PlayerAggressive, 500, -500, 270)
    bubble.u2 = Unit(TPL_UNIT.AttackMode2, PlayerAggressive, -500, -1500, 270)
    bubble.u3 = Unit(TPL_UNIT.AttackMode3, PlayerAggressive, 500, -1500, 270)
    bubble.u4 = Unit(TPL_UNIT.AttackMode4, PlayerAggressive, 0, -500, 270)
    bubble.u5 = Unit(TPL_UNIT.AttackMode5, PlayerAggressive, 0, -1500, 270)

end)