TPL_UNIT.AttackMode0 = UnitTpl()
    :move(5)
    :modelAlias("Footman")
    :icon("unit\\Footman")
    :superposition("noAttack", 1)
    :hp(999999)

TPL_UNIT.AttackMode1 = UnitTpl()
    :move(5)
    :modelAlias("Footman")
    :icon("unit\\Footman")
    :superposition("noAttack", 1)
    :hp(999999)
    :flyHeight(200)

TPL_UNIT.AttackMode2 = UnitTpl()
    :move(5)
    :modelAlias("Footman")
    :icon("unit\\Footman")
    :superposition("noAttack", 1)
    :hp(999999)
    :stature(100)

TPL_UNIT.AttackMode3 = UnitTpl()
    :move(5)
    :modelAlias("Footman")
    :icon("unit\\Footman")
    :superposition("noAttack", 1)
    :hp(999999)
    :flyHeight(200)
    :stature(100)

TPL_UNIT.AttackMode4 = UnitTpl()
    :move(5)
    :modelAlias("Footman")
    :icon("unit\\Footman")
    :superposition("noAttack", 1)
    :hp(999999)
    :flyHeight(400)
    :stature(30)

TPL_UNIT.AttackMode5 = UnitTpl()
    :move(5)
    :modelAlias("Footman")
    :icon("unit\\Footman")
    :superposition("noAttack", 1)
    :hp(999999)
    :flyHeight(400)
    :stature(30)
