TPL_UNIT.Footman = UnitTpl("Footman")
    :modelAlias("Footman")
    :icon("unit\\Footman")
--:superposition("noAttack", 1)
    :weaponSound("metal_slice_medium")
    :itemSlot({ TPL_ITEM.IT1, TPL_ITEM.IT2 })
    :elite(true)
    :reborn(5)
    :rebornHP(60)
    :rebornMP(40)
    :hp(1000):hpRegen(50)
    :mp(1000):mpRegen(10)
    :move(522)
    :attackSpaceBase(0.7)
    :attack(77)
    :attackRange(1000)
    :attackMode(AttackMode():mode("lightning"):lightningType(LIGHTNING_TYPE.suckBlue):focus(3):damageType(DAMAGE_TYPE.thunder))

TPL_UNIT.FootmanAvatar = UnitTpl("Footman")
    :speechExtra("avatar")
    :modelAlias("Footman")
    :icon("unit\\Footman")
    :superposition("noAttack", 1)
    :itemSlot({ TPL_ITEM.IT1, TPL_ITEM.IT2 })
    :elite(true)
    :reborn(5)
    :rebornHP(60)
    :rebornMP(40)
    :hp(1000):hpRegen(50)
    :mp(1000):mpRegen(10)
    :move(522)
    :attackSpaceBase(0.7)
    :attack(77)
    :attackRange(1000)
    :attackMode(AttackMode():mode("lightning"):lightningType(LIGHTNING_TYPE.suckBlue):focus(3):damageType(DAMAGE_TYPE.thunder))

TPL_UNIT.FootmanBuilding = UnitTpl("Footman")
    :speechExtra("building")
    :modelAlias("Footman")
    :icon("unit\\Footman")
    :superposition("noAttack", 1)
    :itemSlot({ TPL_ITEM.IT1, TPL_ITEM.IT2 })
    :elite(true)
    :reborn(5)
    :rebornHP(60)
    :rebornMP(40)
    :hp(1000):hpRegen(50)
    :mp(1000):mpRegen(10)
    :move(522)
    :attackSpaceBase(0.7)
    :attack(77)
    :attackRange(1000)
    :attackMode(AttackMode():mode("lightning"):lightningType(LIGHTNING_TYPE.suckBlue):focus(3):damageType(DAMAGE_TYPE.thunder))

TPL_UNIT.FootmanBuildingMove = UnitTpl("Footman")
    :speechExtra("buildingMove")
    :modelAlias("Footman")
    :icon("unit\\Footman")
    :superposition("noAttack", 1)
    :itemSlot({ TPL_ITEM.IT1, TPL_ITEM.IT2 })
    :elite(true)
    :reborn(5)
    :rebornHP(60)
    :rebornMP(40)
    :hp(1000):hpRegen(50)
    :mp(1000):mpRegen(10)
    :move(522)
    :attackSpaceBase(0.7)
    :attack(77)
    :attackRange(1000)
    :attackMode(AttackMode():mode("lightning"):lightningType(LIGHTNING_TYPE.suckBlue):focus(3):damageType(DAMAGE_TYPE.thunder))